runtime: python38 # or python37 for Python 3.7
handlers:
# Matches requests to /images/... to files in static/images/...
- url: /media
static_dir: static/media
- url: /static
static_dir: staticfiles/
- url: /.*
secure: always
redirect_http_response_code: 301
script: auto
