# Generated by Django 3.1 on 2020-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='colour',
        ),
        migrations.AddField(
            model_name='course',
            name='qualification',
            field=models.SmallIntegerField(default=0, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Curso'),
        ),
    ]
