# Generated by Django 3.1 on 2020-08-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200816_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='colour',
            field=models.CharField(choices=[('yellow', 'Amarillo'), ('light-brown', 'Marrón Claro'), ('orange', 'Naranja'), ('red', 'Rojo'), ('pink', 'Rosado'), ('turquoise', 'Turquesa'), ('light-green', 'Verde Claro'), ('green', 'Verde')], default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Imagen de Presentación'),
        ),
    ]
