# Generated by Django 3.1 on 2020-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201009_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.SmallIntegerField(default=10, verbose_name='Precio'),
        ),
    ]
