# Generated by Django 3.1 on 2020-08-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200816_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='colour',
            field=models.CharField(choices=[('yellow', 'Amarillo'), ('light-brown', 'Marrón Claro'), ('orange', 'Naranja'), ('red', 'Rojo'), ('violet', 'Violeta'), ('turquoise', 'Turquesa'), ('green', 'Verde')], default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.CharField(max_length=20, verbose_name='Video de Presentación'),
        ),
    ]
