# Generated by Django 3.1 on 2020-10-12 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100, verbose_name='Pregunta')),
                ('answer', models.CharField(max_length=255, verbose_name='Respuesta')),
                ('order', models.IntegerField(default=5, verbose_name='Orden de Prioridades')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course')),
            ],
        ),
    ]
