# Generated by Django 3.1 on 2020-10-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id', 'order'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AddField(
            model_name='instructor',
            name='description',
            field=models.TextField(default='Vacio', verbose_name='Descripción'),
        ),
    ]
