# Generated by Django 3.1 on 2020-10-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201012_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Link de su Pagina de FB'),
        ),
    ]
