# Generated by Django 3.1 on 2020-10-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201012_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructor', verbose_name='Imagen de Perfil'),
        ),
    ]
