# Generated by Django 3.1 on 2020-10-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_instructor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='subtitulo',
            field=models.CharField(default='Vacio', max_length=100, verbose_name='Subtitulo del Instructor'),
        ),
    ]
