# Generated by Django 3.1 on 2020-10-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_instructor_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='date_created',
        ),
    ]
