# Generated by Django 3.1 on 2020-10-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_instructor_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='qualification',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Calificación'),
        ),
    ]
