# Generated by Django 3.1 on 2020-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('phone_code', models.CharField(max_length=10)),
            ],
        ),
    ]
