# Generated by Django 3.1 on 2020-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20201010_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
